# Generated by Django 2.1.5 on 2019-01-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReducedRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateField()),
                ('data_end', models.DateField()),
                ('hour_ini', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
