# Generated by Django 2.1.5 on 2019-01-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateTimeField()),
                ('raw_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_day', models.IntegerField()),
                ('hour_minute', models.TimeField()),
                ('t_average', models.IntegerField()),
                ('t_count', models.IntegerField()),
                ('t_control', models.BooleanField(default=False)),
            ],
        ),
    ]
